config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: %i[new create]

    collection do
      get :top
    end

    member do
      get :chef
    end
  end

  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy chef ]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def chef
    @chef_name = @restaurant.chef_name
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :rating)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBeyondCrud1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= '⭐' * restaurant.rating %>
  </p>

  <div class="d-flex justify-content-between">
    <p>
      <%= link_to 'see chef', chef_restaurant_path(restaurant) %>
    </p>
    <p>
      <%= link_to 'write review', new_restaurant_review_path(restaurant) %>
    </p>
  </div>

</div>

app/views/restaurants/chef.html.erb
<div class="container col-4 my-5">
  <h1><%= @restaurant.name %>'s Chef</h1>
  <p><%= @chef_name %></p>
  <%= link_to "Back to restaurant", restaurant_path(@restaurant), class: "btn btn-primary" %>
</div>

app/views/restaurants/edit.html.erb
<div class="container col-4 my-3">
  <h1>Editing restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <br>

  <div class="d-flex justify-content-between">
    <%= link_to "Show this restaurant", @restaurant, class: "btn btn-primary" %>
    <%= link_to "Back to restaurants", restaurants_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="d-flex justify-content-between">
    <h1>Restaurants</h1>
    <%= link_to "Top Restaurants (5 stars)", top_restaurants_path, class: "d-flex btn btn-primary align-items-center" %>
  </div>

  <div id="restaurants">
    <% @restaurants.each do |restaurant| %>
      <hr>
      <%= render restaurant %>
      <p>
        <%= link_to "Show this restaurant", restaurant, class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>


  <hr>
  <br>

  <%= link_to "New restaurant", new_restaurant_path, class: 'btn btn-primary mb-5' %>

</div>

app/views/restaurants/new.html.erb
<div class="container col-4 py-5">
  <h1 class="my-4 text-center">New restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <br>

  <div>
    <%= link_to "Back to restaurants", restaurants_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container col-6 mt-5">
  <p style="color: green"><%= notice %></p>

  <%= render @restaurant %>

  <p><strong>Reviews</strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item d-flex justify-content-between">
        <%= review.content %>
        <%= link_to "Delete",
          review_path(review),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
      </li>
    <% end %>
  </ul>
  <br>

  <div class="d-flex justify-content-between mb-5">
    <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant), class: "btn btn-primary" %>
    <%= link_to "Back to restaurants", restaurants_path, class: "btn btn-primary" %>
  </div>
    <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>

app/views/restaurants/top.html.erb
<div class="container col-6 my-3">
  <h1>5 Stars Restaurants</h1>
  <div id="restaurants">
    <% @restaurants.each do |restaurant| %>
      <hr>
      <%= render restaurant %>
      <p>
        <%= link_to "Show this restaurant", restaurant, class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>

</div>

app/views/reviews/new.html.erb
<div class="container col-4 my-3">
  <h1>New review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>